default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: workouts-api_development
test:
  <<: *default
  database: workouts-api_test
production:
  <<: *default
  database: workouts-api_production
